version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:$ENV
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist s3://$S3_BUCKET_NAME/ 