version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i yarn -g
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build:$ENV
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist s3://$S3_BUCKET_NAME/ 