// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'ap-northeast-2',
  'aws_cognito_identity_pool_id': 'ap-northeast-2:7fe34976-0644-4878-a01b-c77731a314e9',
  'aws_cognito_region': 'ap-northeast-2',
  'aws_user_pools_id': 'ap-northeast-2_K2f6QM7iF',
  'aws_user_pools_web_client_id': '6m54119506mkh6dvhiiampagv',
  'oauth': {},
  'aws_user_files_s3_bucket': '4rtong-staging-imagesartongvue-artongvue',
  'aws_user_files_s3_bucket_region': 'ap-northeast-2'
}

export default awsmobile
